
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codo_a_codo_griselda
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
        
  
    
